#include "telemetry.h"
#include "vospi.h"

telemetry_data_t parse_telemetry_packet(vospi_packet_t* packet)
{
  //uint32_t reordered_status_bits = LEPTON_DWORD(packet->symbols, 6);

  // Decode the status bits first
  // telemetry_data_status_bits_t status_bits = {
  //   .ffc_desired = (reordered_status_bits & 0x08) >> 3,
  //   .ffc_state = (reordered_status_bits & 0x30) >> 4,
  //   .agc_state = (reordered_status_bits & 0x1000) >> 12,
  //   .shutter_lockout = (reordered_status_bits & 0x4000) >> 15,
  //   .overtemp_shutdown_imminent = (reordered_status_bits & 0x100000) >> 20
  // };

  telemetry_data_t telemetry_data = {

    //A Register
    // .revision = LEPTON_WORD(packet->symbols, 0),
    // .msec_since_boot = LEPTON_DWORD(packet->symbols, 2),
    // .status_bits = status_bits,
    // .frame_count = LEPTON_DWORD(packet->symbols, 40),
    // .frame_mean = LEPTON_WORD(packet->symbols, 44),
    // .fpa_temp_count = LEPTON_WORD(packet->symbols, 46),
    // .fpa_temp_kelvin_100 = LEPTON_WORD(packet->symbols, 48),
    // .fpa_temp_last_ffc_kelvin_100 = LEPTON_WORD(packet->symbols, 58),
    // .msec_last_ffc = LEPTON_DWORD(packet->symbols, 60),
    // .agc_roi_top = LEPTON_WORD(packet->symbols, 68),
    // .agc_roi_left = LEPTON_WORD(packet->symbols, 70),
    // .agc_roi_bottom = LEPTON_WORD(packet->symbols, 72),
    // .agc_roi_right = LEPTON_WORD(packet->symbols, 74),
    // .agc_clip_limit_high = LEPTON_WORD(packet->symbols, 76),
    // .agc_clip_limit_low = LEPTON_WORD(packet->symbols, 78),
    // .video_output_format = LEPTON_DWORD(packet->symbols, 144)

    //B Register
    // .background_temp = LEPTON_WORD(packet->symbols,20)

    //C Register
    // .tlinear_resolution = LEPTON_WORD(packet->symbols,98),
    // .spotmeter_mean_temp = LEPTON_WORD(packet->symbols,100),
    // .spotmeter_max_temp = LEPTON_WORD(packet->symbols,102),
    // .spotmeter_min_temp = LEPTON_WORD(packet->symbols,104),
    // .spotmeter_population = LEPTON_WORD(packet->symbols,106),
    // .spotmeter_start_row = LEPTON_WORD(packet->symbols,108),
    // .spotmeter_start_col = LEPTON_WORD(packet->symbols,110),
    // .spotmeter_end_row = LEPTON_WORD(packet->symbols,112),
    // .spotmeter_end_col = LEPTON_WORD(packet->symbols,114)

    .variable0 = LEPTON_WORD(packet->symbols,0),
.variable1 = LEPTON_WORD(packet->symbols,1),
.variable2 = LEPTON_WORD(packet->symbols,2),
.variable3 = LEPTON_WORD(packet->symbols,3),
.variable4 = LEPTON_WORD(packet->symbols,4),
.variable5 = LEPTON_WORD(packet->symbols,5),
.variable6 = LEPTON_WORD(packet->symbols,6),
.variable7 = LEPTON_WORD(packet->symbols,7),
.variable8 = LEPTON_WORD(packet->symbols,8),
.variable9 = LEPTON_WORD(packet->symbols,9),
.variable10 = LEPTON_WORD(packet->symbols,10),
.variable11 = LEPTON_WORD(packet->symbols,11),
.variable12 = LEPTON_WORD(packet->symbols,12),
.variable13 = LEPTON_WORD(packet->symbols,13),
.variable14 = LEPTON_WORD(packet->symbols,14),
.variable15 = LEPTON_WORD(packet->symbols,15),
.variable16 = LEPTON_WORD(packet->symbols,16),
.variable17 = LEPTON_WORD(packet->symbols,17),
.variable18 = LEPTON_WORD(packet->symbols,18),
.variable19 = LEPTON_WORD(packet->symbols,19),
.variable20 = LEPTON_WORD(packet->symbols,20),
.variable21 = LEPTON_WORD(packet->symbols,21),
.variable22 = LEPTON_WORD(packet->symbols,22),
.variable23 = LEPTON_WORD(packet->symbols,23),
.variable24 = LEPTON_WORD(packet->symbols,24),
.variable25 = LEPTON_WORD(packet->symbols,25),
.variable26 = LEPTON_WORD(packet->symbols,26),
.variable27 = LEPTON_WORD(packet->symbols,27),
.variable28 = LEPTON_WORD(packet->symbols,28),
.variable29 = LEPTON_WORD(packet->symbols,29),
.variable30 = LEPTON_WORD(packet->symbols,30),
.variable31 = LEPTON_WORD(packet->symbols,31),
.variable32 = LEPTON_WORD(packet->symbols,32),
.variable33 = LEPTON_WORD(packet->symbols,33),
.variable34 = LEPTON_WORD(packet->symbols,34),
.variable35 = LEPTON_WORD(packet->symbols,35),
.variable36 = LEPTON_WORD(packet->symbols,36),
.variable37 = LEPTON_WORD(packet->symbols,37),
.variable38 = LEPTON_WORD(packet->symbols,38),
.variable39 = LEPTON_WORD(packet->symbols,39),
.variable40 = LEPTON_WORD(packet->symbols,40),
.variable41 = LEPTON_WORD(packet->symbols,41),
.variable42 = LEPTON_WORD(packet->symbols,42),
.variable43 = LEPTON_WORD(packet->symbols,43),
.variable44 = LEPTON_WORD(packet->symbols,44),
.variable45 = LEPTON_WORD(packet->symbols,45),
.variable46 = LEPTON_WORD(packet->symbols,46),
.variable47 = LEPTON_WORD(packet->symbols,47),
.variable48 = LEPTON_WORD(packet->symbols,48),
.variable49 = LEPTON_WORD(packet->symbols,49),
.variable50 = LEPTON_WORD(packet->symbols,50),
.variable51 = LEPTON_WORD(packet->symbols,51),
.variable52 = LEPTON_WORD(packet->symbols,52),
.variable53 = LEPTON_WORD(packet->symbols,53),
.variable54 = LEPTON_WORD(packet->symbols,54),
.variable55 = LEPTON_WORD(packet->symbols,55),
.variable56 = LEPTON_WORD(packet->symbols,56),
.variable57 = LEPTON_WORD(packet->symbols,57),
.variable58 = LEPTON_WORD(packet->symbols,58),
.variable59 = LEPTON_WORD(packet->symbols,59),
.variable60 = LEPTON_WORD(packet->symbols,60),
.variable61 = LEPTON_WORD(packet->symbols,61),
.variable62 = LEPTON_WORD(packet->symbols,62),
.variable63 = LEPTON_WORD(packet->symbols,63),
.variable64 = LEPTON_WORD(packet->symbols,64),
.variable65 = LEPTON_WORD(packet->symbols,65),
.variable66 = LEPTON_WORD(packet->symbols,66),
.variable67 = LEPTON_WORD(packet->symbols,67),
.variable68 = LEPTON_WORD(packet->symbols,68),
.variable69 = LEPTON_WORD(packet->symbols,69),
.variable70 = LEPTON_WORD(packet->symbols,70),
.variable71 = LEPTON_WORD(packet->symbols,71),
.variable72 = LEPTON_WORD(packet->symbols,72),
.variable73 = LEPTON_WORD(packet->symbols,73),
.variable74 = LEPTON_WORD(packet->symbols,74),
.variable75 = LEPTON_WORD(packet->symbols,75),
.variable76 = LEPTON_WORD(packet->symbols,76),
.variable77 = LEPTON_WORD(packet->symbols,77),
.variable78 = LEPTON_WORD(packet->symbols,78),
.variable79 = LEPTON_WORD(packet->symbols,79),
.variable80 = LEPTON_WORD(packet->symbols,80),
.variable81 = LEPTON_WORD(packet->symbols,81),
.variable82 = LEPTON_WORD(packet->symbols,82),
.variable83 = LEPTON_WORD(packet->symbols,83),
.variable84 = LEPTON_WORD(packet->symbols,84),
.variable85 = LEPTON_WORD(packet->symbols,85),
.variable86 = LEPTON_WORD(packet->symbols,86),
.variable87 = LEPTON_WORD(packet->symbols,87),
.variable88 = LEPTON_WORD(packet->symbols,88),
.variable89 = LEPTON_WORD(packet->symbols,89),
.variable90 = LEPTON_WORD(packet->symbols,90),
.variable91 = LEPTON_WORD(packet->symbols,91),
.variable92 = LEPTON_WORD(packet->symbols,92),
.variable93 = LEPTON_WORD(packet->symbols,93),
.variable94 = LEPTON_WORD(packet->symbols,94),
.variable95 = LEPTON_WORD(packet->symbols,95),
.variable96 = LEPTON_WORD(packet->symbols,96),
.variable97 = LEPTON_WORD(packet->symbols,97),
.variable98 = LEPTON_WORD(packet->symbols,98),
.variable99 = LEPTON_WORD(packet->symbols,99),
.variable100 = LEPTON_WORD(packet->symbols,100),
.variable101 = LEPTON_WORD(packet->symbols,101),
.variable102 = LEPTON_WORD(packet->symbols,102),
.variable103 = LEPTON_WORD(packet->symbols,103),
.variable104 = LEPTON_WORD(packet->symbols,104),
.variable105 = LEPTON_WORD(packet->symbols,105),
.variable106 = LEPTON_WORD(packet->symbols,106),
.variable107 = LEPTON_WORD(packet->symbols,107),
.variable108 = LEPTON_WORD(packet->symbols,108),
.variable109 = LEPTON_WORD(packet->symbols,109),
.variable110 = LEPTON_WORD(packet->symbols,110),
.variable111 = LEPTON_WORD(packet->symbols,111),
.variable112 = LEPTON_WORD(packet->symbols,112),
.variable113 = LEPTON_WORD(packet->symbols,113),
.variable114 = LEPTON_WORD(packet->symbols,114),
.variable115 = LEPTON_WORD(packet->symbols,115),
.variable116 = LEPTON_WORD(packet->symbols,116),
.variable117 = LEPTON_WORD(packet->symbols,117),
.variable118 = LEPTON_WORD(packet->symbols,118),
.variable119 = LEPTON_WORD(packet->symbols,119),
.variable120 = LEPTON_WORD(packet->symbols,120),
.variable121 = LEPTON_WORD(packet->symbols,121),
.variable122 = LEPTON_WORD(packet->symbols,122),
.variable123 = LEPTON_WORD(packet->symbols,123),
.variable124 = LEPTON_WORD(packet->symbols,124),
.variable125 = LEPTON_WORD(packet->symbols,125),
.variable126 = LEPTON_WORD(packet->symbols,126),
.variable127 = LEPTON_WORD(packet->symbols,127),
.variable128 = LEPTON_WORD(packet->symbols,128),
.variable129 = LEPTON_WORD(packet->symbols,129),
.variable130 = LEPTON_WORD(packet->symbols,130),
.variable131 = LEPTON_WORD(packet->symbols,131),
.variable132 = LEPTON_WORD(packet->symbols,132),
.variable133 = LEPTON_WORD(packet->symbols,133),
.variable134 = LEPTON_WORD(packet->symbols,134),
.variable135 = LEPTON_WORD(packet->symbols,135),
.variable136 = LEPTON_WORD(packet->symbols,136),
.variable137 = LEPTON_WORD(packet->symbols,137),
.variable138 = LEPTON_WORD(packet->symbols,138),
.variable139 = LEPTON_WORD(packet->symbols,139),
.variable140 = LEPTON_WORD(packet->symbols,140),
.variable141 = LEPTON_WORD(packet->symbols,141),
.variable142 = LEPTON_WORD(packet->symbols,142),
.variable143 = LEPTON_WORD(packet->symbols,143),
.variable144 = LEPTON_WORD(packet->symbols,144),
.variable145 = LEPTON_WORD(packet->symbols,145),
.variable146 = LEPTON_WORD(packet->symbols,146),
.variable147 = LEPTON_WORD(packet->symbols,147),
.variable148 = LEPTON_WORD(packet->symbols,148),
.variable149 = LEPTON_WORD(packet->symbols,149),
.variable150 = LEPTON_WORD(packet->symbols,150),
.variable151 = LEPTON_WORD(packet->symbols,151),
.variable152 = LEPTON_WORD(packet->symbols,152),
.variable153 = LEPTON_WORD(packet->symbols,153),
.variable154 = LEPTON_WORD(packet->symbols,154),
.variable155 = LEPTON_WORD(packet->symbols,155),
.variable156 = LEPTON_WORD(packet->symbols,156),
.variable157 = LEPTON_WORD(packet->symbols,157),
.variable158 = LEPTON_WORD(packet->symbols,158),
.variable159 = LEPTON_WORD(packet->symbols,159),
.variable160 = LEPTON_WORD(packet->symbols,160),
.variable161 = LEPTON_WORD(packet->symbols,161),
.variable162 = LEPTON_WORD(packet->symbols,162),
.variable163 = LEPTON_WORD(packet->symbols,163),
.variable164 = LEPTON_WORD(packet->symbols,164),
.variable165 = LEPTON_WORD(packet->symbols,165),
.variable166 = LEPTON_WORD(packet->symbols,166),
.variable167 = LEPTON_WORD(packet->symbols,167),
.variable168 = LEPTON_WORD(packet->symbols,168),
.variable169 = LEPTON_WORD(packet->symbols,169),
.variable170 = LEPTON_WORD(packet->symbols,170),
.variable171 = LEPTON_WORD(packet->symbols,171),
.variable172 = LEPTON_WORD(packet->symbols,172),
.variable173 = LEPTON_WORD(packet->symbols,173),
.variable174 = LEPTON_WORD(packet->symbols,174),
.variable175 = LEPTON_WORD(packet->symbols,175),
.variable176 = LEPTON_WORD(packet->symbols,176),
.variable177 = LEPTON_WORD(packet->symbols,177),
.variable178 = LEPTON_WORD(packet->symbols,178),
.variable179 = LEPTON_WORD(packet->symbols,179)



  };

  return telemetry_data;
}
