#include "telemetry.h"
#include "vospi.h"

telemetry_data_t parse_telemetry_packet(vospi_packet_t* packet)
{
  //uint32_t reordered_status_bits = LEPTON_DWORD(packet->symbols, 6);

  // Decode the status bits first
  // telemetry_data_status_bits_t status_bits = {
  //   .ffc_desired = (reordered_status_bits & 0x08) >> 3,
  //   .ffc_state = (reordered_status_bits & 0x30) >> 4,
  //   .agc_state = (reordered_status_bits & 0x1000) >> 12,
  //   .shutter_lockout = (reordered_status_bits & 0x4000) >> 15,
  //   .overtemp_shutdown_imminent = (reordered_status_bits & 0x100000) >> 20
  // };

  telemetry_data_t telemetry_data = {

    //A Register
    // .revision = LEPTON_WORD(packet->symbols, 0),
    // .msec_since_boot = LEPTON_DWORD(packet->symbols, 2),
    // .status_bits = status_bits,
    // .frame_count = LEPTON_DWORD(packet->symbols, 40),
    // .frame_mean = LEPTON_WORD(packet->symbols, 44),
    // .fpa_temp_count = LEPTON_WORD(packet->symbols, 46),
    // .fpa_temp_kelvin_100 = LEPTON_WORD(packet->symbols, 48),
    // .fpa_temp_last_ffc_kelvin_100 = LEPTON_WORD(packet->symbols, 58),
    // .msec_last_ffc = LEPTON_DWORD(packet->symbols, 60),
    // .agc_roi_top = LEPTON_WORD(packet->symbols, 68),
    // .agc_roi_left = LEPTON_WORD(packet->symbols, 70),
    // .agc_roi_bottom = LEPTON_WORD(packet->symbols, 72),
    // .agc_roi_right = LEPTON_WORD(packet->symbols, 74),
    // .agc_clip_limit_high = LEPTON_WORD(packet->symbols, 76),
    // .agc_clip_limit_low = LEPTON_WORD(packet->symbols, 78),
    // .video_output_format = LEPTON_DWORD(packet->symbols, 144)

    //B Register
    // .background_temp = LEPTON_WORD(packet->symbols,20)

    //C Register
    // .gain_mode = LEPTON_WORD(packet->symbols,5),
    // .effective_gain = LEPTON_WORD(packet->symbols,6),

    // .temp_gain_mode_high_to_low = LEPTON_WORD(packet->symbols,8),


    // .tlinear_resolution = LEPTON_WORD(packet->symbols,49),
    // .spotmeter_mean_temp = LEPTON_WORD(packet->symbols,50),
    // .spotmeter_max_temp = LEPTON_WORD(packet->symbols,51),
    // .spotmeter_min_temp = LEPTON_WORD(packet->symbols,52),
    // .spotmeter_population = LEPTON_WORD(packet->symbols,53),
    // .spotmeter_start_row = LEPTON_WORD(packet->symbols,54),
    // .spotmeter_start_col = LEPTON_WORD(packet->symbols,55),
    // .spotmeter_end_row = LEPTON_WORD(packet->symbols,56),
    // .spotmeter_end_col = LEPTON_WORD(packet->symbols,7)



    .a = LEPTON_WORD(packet->symbols,0),
.b = LEPTON_WORD(packet->symbols,1),
.c = LEPTON_WORD(packet->symbols,2),
.d = LEPTON_WORD(packet->symbols,3),
.e = LEPTON_WORD(packet->symbols,4),
.f = LEPTON_WORD(packet->symbols,5),
.g = LEPTON_WORD(packet->symbols,6),
.h = LEPTON_WORD(packet->symbols,7),
.i = LEPTON_WORD(packet->symbols,8),
.j = LEPTON_WORD(packet->symbols,9),
.k = LEPTON_WORD(packet->symbols,10),
.l = LEPTON_WORD(packet->symbols,11),
.m = LEPTON_WORD(packet->symbols,12),
.n = LEPTON_WORD(packet->symbols,13),
.o = LEPTON_WORD(packet->symbols,14),
.p = LEPTON_WORD(packet->symbols,15),
.q = LEPTON_WORD(packet->symbols,16),
.r = LEPTON_WORD(packet->symbols,17),
.s = LEPTON_WORD(packet->symbols,18),
.t = LEPTON_WORD(packet->symbols,19),
.u = LEPTON_WORD(packet->symbols,20),
.v = LEPTON_WORD(packet->symbols,21),
.w = LEPTON_WORD(packet->symbols,22),
.x = LEPTON_WORD(packet->symbols,23),
.y = LEPTON_WORD(packet->symbols,24),
.z = LEPTON_WORD(packet->symbols,25),
.{ = LEPTON_WORD(packet->symbols,26),
.| = LEPTON_WORD(packet->symbols,27),
.} = LEPTON_WORD(packet->symbols,28),
.~ = LEPTON_WORD(packet->symbols,29),
. = LEPTON_WORD(packet->symbols,30),
. = LEPTON_WORD(packet->symbols,31),
. = LEPTON_WORD(packet->symbols,32),
. = LEPTON_WORD(packet->symbols,33),
. = LEPTON_WORD(packet->symbols,34),
. = LEPTON_WORD(packet->symbols,35),
. = LEPTON_WORD(packet->symbols,36),
. = LEPTON_WORD(packet->symbols,37),
. = LEPTON_WORD(packet->symbols,38),
. = LEPTON_WORD(packet->symbols,39),
. = LEPTON_WORD(packet->symbols,40),
. = LEPTON_WORD(packet->symbols,41),
. = LEPTON_WORD(packet->symbols,42),
. = LEPTON_WORD(packet->symbols,43),
. = LEPTON_WORD(packet->symbols,44),
. = LEPTON_WORD(packet->symbols,45),
. = LEPTON_WORD(packet->symbols,46),
. = LEPTON_WORD(packet->symbols,47),
. = LEPTON_WORD(packet->symbols,48),
. = LEPTON_WORD(packet->symbols,49),
. = LEPTON_WORD(packet->symbols,50),
. = LEPTON_WORD(packet->symbols,51),
. = LEPTON_WORD(packet->symbols,52),
. = LEPTON_WORD(packet->symbols,53),
. = LEPTON_WORD(packet->symbols,54),
. = LEPTON_WORD(packet->symbols,55),
. = LEPTON_WORD(packet->symbols,56),
. = LEPTON_WORD(packet->symbols,57),
. = LEPTON_WORD(packet->symbols,58),
. = LEPTON_WORD(packet->symbols,59),
. = LEPTON_WORD(packet->symbols,60),
. = LEPTON_WORD(packet->symbols,61),
. = LEPTON_WORD(packet->symbols,62),
.  = LEPTON_WORD(packet->symbols,63),
.¡ = LEPTON_WORD(packet->symbols,64),
.¢ = LEPTON_WORD(packet->symbols,65),
.£ = LEPTON_WORD(packet->symbols,66),
.¤ = LEPTON_WORD(packet->symbols,67),
.¥ = LEPTON_WORD(packet->symbols,68),
.¦ = LEPTON_WORD(packet->symbols,69),
.§ = LEPTON_WORD(packet->symbols,70),
.¨ = LEPTON_WORD(packet->symbols,71),
.© = LEPTON_WORD(packet->symbols,72),
.ª = LEPTON_WORD(packet->symbols,73),
.« = LEPTON_WORD(packet->symbols,74),
.¬ = LEPTON_WORD(packet->symbols,75),
.­ = LEPTON_WORD(packet->symbols,76),
.® = LEPTON_WORD(packet->symbols,77),
.¯ = LEPTON_WORD(packet->symbols,78),
.° = LEPTON_WORD(packet->symbols,79),
.± = LEPTON_WORD(packet->symbols,80),
.² = LEPTON_WORD(packet->symbols,81),
.³ = LEPTON_WORD(packet->symbols,82),
.´ = LEPTON_WORD(packet->symbols,83),
.µ = LEPTON_WORD(packet->symbols,84),
.¶ = LEPTON_WORD(packet->symbols,85),
.· = LEPTON_WORD(packet->symbols,86),
.¸ = LEPTON_WORD(packet->symbols,87),
.¹ = LEPTON_WORD(packet->symbols,88),
.º = LEPTON_WORD(packet->symbols,89),
.» = LEPTON_WORD(packet->symbols,90),
.¼ = LEPTON_WORD(packet->symbols,91),
.½ = LEPTON_WORD(packet->symbols,92),
.¾ = LEPTON_WORD(packet->symbols,93),
.¿ = LEPTON_WORD(packet->symbols,94),
.À = LEPTON_WORD(packet->symbols,95),
.Á = LEPTON_WORD(packet->symbols,96),
.Â = LEPTON_WORD(packet->symbols,97),
.Ã = LEPTON_WORD(packet->symbols,98),
.Ä = LEPTON_WORD(packet->symbols,99),
.Å = LEPTON_WORD(packet->symbols,100),
.Æ = LEPTON_WORD(packet->symbols,101),
.Ç = LEPTON_WORD(packet->symbols,102),
.È = LEPTON_WORD(packet->symbols,103),
.É = LEPTON_WORD(packet->symbols,104),
.Ê = LEPTON_WORD(packet->symbols,105),
.Ë = LEPTON_WORD(packet->symbols,106),
.Ì = LEPTON_WORD(packet->symbols,107),
.Í = LEPTON_WORD(packet->symbols,108),
.Î = LEPTON_WORD(packet->symbols,109),
.Ï = LEPTON_WORD(packet->symbols,110),
.Ð = LEPTON_WORD(packet->symbols,111),
.Ñ = LEPTON_WORD(packet->symbols,112),
.Ò = LEPTON_WORD(packet->symbols,113),
.Ó = LEPTON_WORD(packet->symbols,114),
.Ô = LEPTON_WORD(packet->symbols,115),
.Õ = LEPTON_WORD(packet->symbols,116),
.Ö = LEPTON_WORD(packet->symbols,117),
.× = LEPTON_WORD(packet->symbols,118),
.Ø = LEPTON_WORD(packet->symbols,119),
.Ù = LEPTON_WORD(packet->symbols,120),
.Ú = LEPTON_WORD(packet->symbols,121),
.Û = LEPTON_WORD(packet->symbols,122),
.Ü = LEPTON_WORD(packet->symbols,123),
.Ý = LEPTON_WORD(packet->symbols,124),
.Þ = LEPTON_WORD(packet->symbols,125),
.ß = LEPTON_WORD(packet->symbols,126),
.à = LEPTON_WORD(packet->symbols,127),
.á = LEPTON_WORD(packet->symbols,128),
.â = LEPTON_WORD(packet->symbols,129),
.ã = LEPTON_WORD(packet->symbols,130),
.ä = LEPTON_WORD(packet->symbols,131),
.å = LEPTON_WORD(packet->symbols,132),
.æ = LEPTON_WORD(packet->symbols,133),
.ç = LEPTON_WORD(packet->symbols,134),
.è = LEPTON_WORD(packet->symbols,135),
.é = LEPTON_WORD(packet->symbols,136),
.ê = LEPTON_WORD(packet->symbols,137),
.ë = LEPTON_WORD(packet->symbols,138),
.ì = LEPTON_WORD(packet->symbols,139),
.í = LEPTON_WORD(packet->symbols,140),
.î = LEPTON_WORD(packet->symbols,141),
.ï = LEPTON_WORD(packet->symbols,142),
.ð = LEPTON_WORD(packet->symbols,143),
.ñ = LEPTON_WORD(packet->symbols,144),
.ò = LEPTON_WORD(packet->symbols,145),
.ó = LEPTON_WORD(packet->symbols,146),
.ô = LEPTON_WORD(packet->symbols,147),
.õ = LEPTON_WORD(packet->symbols,148),
.ö = LEPTON_WORD(packet->symbols,149),
.÷ = LEPTON_WORD(packet->symbols,150),
.ø = LEPTON_WORD(packet->symbols,151),
.ù = LEPTON_WORD(packet->symbols,152),
.ú = LEPTON_WORD(packet->symbols,153),
.û = LEPTON_WORD(packet->symbols,154),
.ü = LEPTON_WORD(packet->symbols,155),
.ý = LEPTON_WORD(packet->symbols,156),
.þ = LEPTON_WORD(packet->symbols,157),
.ÿ = LEPTON_WORD(packet->symbols,158),
.Ā = LEPTON_WORD(packet->symbols,159),
.ā = LEPTON_WORD(packet->symbols,160),
.Ă = LEPTON_WORD(packet->symbols,161),
.ă = LEPTON_WORD(packet->symbols,162),
.Ą = LEPTON_WORD(packet->symbols,163),
.ą = LEPTON_WORD(packet->symbols,164),
.Ć = LEPTON_WORD(packet->symbols,165),
.ć = LEPTON_WORD(packet->symbols,166),
.Ĉ = LEPTON_WORD(packet->symbols,167),
.ĉ = LEPTON_WORD(packet->symbols,168),
.Ċ = LEPTON_WORD(packet->symbols,169),
.ċ = LEPTON_WORD(packet->symbols,170),
.Č = LEPTON_WORD(packet->symbols,171),
.č = LEPTON_WORD(packet->symbols,172),
.Ď = LEPTON_WORD(packet->symbols,173),
.ď = LEPTON_WORD(packet->symbols,174),
.Đ = LEPTON_WORD(packet->symbols,175),
.đ = LEPTON_WORD(packet->symbols,176),
.Ē = LEPTON_WORD(packet->symbols,177),
.ē = LEPTON_WORD(packet->symbols,178),
.Ĕ = LEPTON_WORD(packet->symbols,179)
    
  };

  return telemetry_data;
}
